Repository jdi-testing/jdi-dark, pull requests merged in 2020-02, with the labels that each got.

#95 Remove rest-assured logs. Add more info to custom logger.
  jdi-dark/src/main/java/com/epam/http/requests/RestMethod.java
  jdi-dark/src/main/java/com/epam/http/requests/RestRequest.java
Labels: logging

#101 Travis stop failed biuld
  .travis.yml
Labels: travis

#93 Task 18 revision 2
  jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/ServiceStepsEN.java
  jdi-dark-tests/src/main/java/com/epam/jdi/httptests/SimpleService.java
  jdi-dark/src/main/java/com/epam/http/requests/RestMethods.java
Labels: CodacyIssue

#121 Fix codacy settings.
  jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java
  jdi-dark-tests/src/main/java/com/epam/jdi/httptests/TrelloApi.java
  jdi-dark/src/main/java/com/epam/http/requests/RestMethods.java
Labels: CodacyIssue

#133 Added doman parameter to .properties and to ServiceInit.
  jdi-dark-tests/src/test/resources/test.properties
  jdi-dark/src/main/java/com/epam/http/JdiHttpSettigns.java
  jdi-dark/src/main/java/com/epam/http/requests/ServiceInit.java
Labels: enhancement

#206 Task 29: Info level codacy issues: Unnecessary use of fully qualifie…
  jdi-dark-bdd/src/main/java/com/epam/jdi/http/stepdefs/en/ResponseStepsEN.java
  jdi-dark-tests/src/main/java/com/epam/jdi/httptests/JettyService.java
Labels: CodacyIssue
